phases:
  pre_build:
    commands:
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  build:
    commands:
      - docker build . -t $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"nginx","imageUri":"danwhite123/task14-nginx_container","portMappings":[{"containerPort":80,"hostPort":80}],"essential":true}]' > imagedefinitions_nginx.json
      - printf '[{"name":"apache","imageUri":"danwhite123/task14-apache_container","portMappings":[{"containerPort":8080,"hostPort":80}],"essential":true}]' > imagedefinitions_apache.json
artifacts:
  files:
    - imagedefinitions_nginx.json
    - imagedefinitions_apache.json
